-- DROPS --

TRUNCATE TABLE couriers CASCADE;
TRUNCATE TABLE customers CASCADE;
TRUNCATE TABLE restaurants CASCADE;
TRUNCATE TABLE menu_items CASCADE;
TRUNCATE TABLE orders CASCADE;
TRUNCATE TABLE order_items CASCADE;