package ru.liga.entities;

public enum OrderStatus {
    CUSTOMER_CREATED, CUSTOMER_PAID, CUSTOMER_CANCELLED,
    KITCHEN_ACCEPTED, KITCHEN_PREPARED, KITCHEN_DENIED, KITCHEN_REFUNDED,
    DELIVERY_PENDING, DELIVERY_PICKING, DELIVERY_DELIVERING, DELIVERY_COMPLETE, DELIVERY_DENIED, DELIVERY_REFUNDED
}
