server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: delivery-service
          uri: http://localhost:8081/
          predicates:
            - Path=/deliveryservice/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: kitchen-service
          uri: http://localhost:8082/
          predicates:
            - Path=/kitchenservice/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: order-service
          uri: http://localhost:8083/
          predicates:
            - Path=/orderservice/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid,message.read
        provider:
          spring:
            issuer-uri: http://localhost:8090